theme: devdocs

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "technologies"
    values:
      toc-group: "technologies"
  -
    scope:
      path: "pwa-buildpack"
    values:
      toc-group: "pwa-buildpack"
  -
    scope:
      path: "peregrine"
    values:
      toc-group: "peregrine"
  -
    scope:
      path: "venia-pwa-concept"
    values:
      toc-group: "venia-pwa-concept"