theme: devdocs

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "technologies"
    values:
      toc-group: "technologies"
  -
    scope:
      path: "peregrine"
    values:
      toc-group: "peregrine"